### ISSUE TITLE
Confustion between java.net.URI and java.net.URL

### ISSUE THREAD

**Issue by gsnewmark** [lambdaisland/uri#1]
AFAIK `java.net.URI::equals` doesn't cause any DNS lookups & class itself allows relative URIs. All problems you've described are present in older class `java.net.URL` (which is used by `cemerick.url`, not sure about other libs mentioned in [Similar projects](https://github.com/lambdaisland/uri#similar-projects)). Please check the post you've [provided in README](http://brian.pontarelli.com/2006/12/05/mr-gosling-why-did-you-make-url-equals-suck/) - it's about `java.net.URL` and specifically says that `java.net.URI` is a better option:
> Argh! This class sucks and I refuse to ever use it again. I’ll always use URI from now on since it doesn’t suck.

**Comment by plexus** [comment]
Thanks for pointing this out, I'll update the README.
