### ISSUE TITLE
Make a new release with url encoding and decoding functions?

### ISSUE THREAD

**Issue by alzadude** [lambdaisland/uri#11]
Hi there,

I see functions for this in `lambdaisland.uri.normalize`, but that's not available in the latest released version. Any chance you could make a release with the url encoding and decoding functions? 

Reason: I'm struggling to find a clj/cljs way of doing this, other than using `cemerick.url` (which I'm trying to move away from, it has some clj/cljs differences, and is no longer maintained).

Thanks!

**Comment by plexus** [comment]
Hi @alzadude, `lambdaisland.uri.normalize` is now available in `1.2.0`
