### ISSUE TITLE
Query param space encoding is inconsistent

### ISSUE THREAD

**Issue by mrrodriguez** [lambdaisland/uri#16]
The follow is unexpected behavior:

```clj
(require '[lambdaisland.uri :as uri])

(-> "/foo"
    (uri/assoc-query* {:a "a b"})
    (uri/assoc-query* {:b "b c"}))
;;= returns
{:scheme nil,
 :user nil,
 :password nil,
 :host nil,
 :port nil, 
 :path "/foo", 
 :query "a=a%2Bb&b=b+c", 
 :fragment nil}
```

Notice that `:query` has confusion around the "+" that is used to encode spaces. This is because all of the "decoding" side query param functions do not take into account the "+".

Another example:
```clj
(-> "/foo"
    (uri/assoc-query* {:a "a b"})
    uri/query-map)
;;= {:a "a+b"}
```
The "+" character is never decoded.

Is this intentional behavior and the expectation is the consumer is careful to always remove "+" at the "right time"?

**Comment by plexus** [comment]
Definitely a bug. I'll fix it.

**Comment by plexus** [comment]
Fixed in 1.4.54. Please close this issue if you've confirmed this fixes things for you. I've added generative testing to make sure encode/decode match up.

**Comment by mrrodriguez** [comment]
@plexus thanks for the fast response! I will test out with the new version and confirm here.

**Comment by mrrodriguez** [comment]
Update: This has been working for me. Thanks for making the changes! I'll close now.
