### ISSUE TITLE
Run CI for PRs from third party branches

### ISSUE THREAD

**Issue by plexus** [lambdaisland/uri#32]
It seems we currently don't run CI on PRs originating from branches on forked repositories. I think this is a Circle CI setting, to prevent leaking secrets, but there are no secrets to leak here. We should fix that, and also review other projects to make sure that if we get contributions the tests actually run.

**Comment by plexus** [comment]
Added this to the [Clojurists Together project board](https://github.com/orgs/lambdaisland/projects/2) even though URI is not officially in scope for this dev cycle, but we should also check the testing-related repos to make sure this is configured correctly.

**Comment by borkdude** [comment]
Project settings -> Advanced Settings -> Flip the switch at Build forked pull requests

<img width="1332" alt="Screenshot 2022-10-10 at 11 57 28" src="https://user-images.githubusercontent.com/284934/194841064-6991a044-20c0-49fb-b0cf-704f34f563db.png">

This doesn't pass secrets to PR builds unless you also flip the switch below.

**Comment by alysbrooks** [comment]
Thanks @borkdude!
