### ISSUE TITLE
`uri` in cljs does not return a `:domain` key

### ISSUE THREAD

**Issue by DrBuchkov** [lambdaisland/uri#34]
From the readme documentation when parsing a uri you should get a `:domain` key.

But running the following example in clojurescript does not return it:
```clj
(keys (uri/uri "example.com"))
; =>  (:scheme :user :password :host :port :path :query :fragment)
```

**Comment by plexus** [comment]
You are right, that seems to be a documentation bug. It should be `:host`, there's no `:domain` key.

Would you be interested in making a PR for the README?
