### ISSUE TITLE
Is there a way to have a predicate for validity?

### ISSUE THREAD

**Issue by jerger** [lambdaisland/uri#43]
Hi,

I like the idea of independent implementation of uri a lot.

Eg. 

```
(uri/uri "https://www.test.com:abcd/test.heml")
(uri/uri "a b")
```

I would expect to be invalid regarding to the RFC. Is there a way to validate such inputs?

**Comment by plexus** [comment]
No, this library does not do validation. Garbage-in, garbage-out.
