### ISSUE TITLE
Accept port as an empty string

### ISSUE THREAD

**Issue by ashwinbhaskar** [lambdaisland/uri#9]
```
(str (-> (uri "/v1/payment")
         (assoc :scheme "https")
         (assoc :host "my.domain.org")
         (assoc :port "")))
```
results in `"https://my.domain.org:/v1/payment"`

The extra `:` in the url causes a problem.

Ideally it should just ignore a blank port.

**Comment by plexus** [comment]
This seems to me like a "garbage in, garbage out" problem. Specs would be useful here though, since port should really be an integer.

**Comment by ashwinbhaskar** [comment]
@plexus This is useful when you have your configurations externalise. This is coming from a practical use case.

**Comment by ashwinbhaskar** [comment]
Any updates here? @plexus
